http://foocafe.org/malmoe/events/1603-artificial-intuition-the-what-how-and-why
http://foocafe.org/malmoe/events/1606-azure-security-devops
http://foocafe.org/malmoe/events/1601-collaborative-sensemaking
http://foocafe.org/malmoe/events/1565-kom-och-lar-dig-koda
http://foocafe.org/malmoe/events/1600-introvert-leadership-my-journey-and-my-tools
http://foocafe.org/malmoe/events/1591-using-coordinators-and-state-machines-to-architect-your-app
http://foocafe.org/malmoe/events/1594-drupal-come-for-the-code-stay-for-the-community
http://foocafe.org/malmoe/events/1610-by-entrepreneurs-for-entrepreneurs
http://foocafe.org/malmoe/events/1613-challenges-i-faced-and-how-i-handled-them
http://foocafe.org/malmoe/events/1596-finite-state-machines-your-compiler-wants-in
http://foocafe.org/malmoe/events/1548-advanced-speakers-club
http://foocafe.org/malmoe/events/1592-holo-world-build-your-first-hololens-app
http://foocafe.org/malmoe/events/1554-want-to-be-a-better-speaker
http://foocafe.org/malmoe/events/1604-want-to-teach-kids-to-code
http://foocafe.org/malmoe/events/1607-are-we-getting-seria-li-ced-yet
http://foocafe.org/malmoe/events/1605-want-to-teach-kids-to-code
http://foocafe.org/malmoe/events/1618-better-sleep-and-less-stress
http://foocafe.org/malmoe/events/1617-respect-software-testing
